### ISSUE TITLE
Missing toJSON methods

### ISSUE THREAD

**Issue by radarfox** [jarek-foksa/geometry-polyfill#3]
Hello,

thank you for the awesome plugin, really helped me a lot.

I have found a little bug to fix, if you are interested. [According to the spec](https://drafts.fxtf.org/geometry/) the `toJSON` method should be defined in `DOMPointReadOnly`, `DOMRectReadOnly`, `DOMQuad` and `DOMMatrixReadOnly`. But it is missing in this polyfill.

```javascript
new DOMRect().toJSON();
// TypeError: Object [object Object] has no method 'toJSON' 
```

Also the `JSON.stringify` method will return different values, than the latest Chrome and Firefox:

```javascript
JSON.stringify(new DOMRect());
// This is returned: {"x":0,"y":0,"width":0,"height":0}
// This should be returned: {"x":0,"y":0,"width":0,"height":0,"top":0,"right":0,"bottom":0,"left":0}
```

This is another difference from the spec, as it requires `top`, `right`, `bottom` and `left` to be enumerable properties, but you use method getters for them, which are not enumerable.

**Comment by jarek-foksa** [comment]
Thanks for feedback, I have addressed those issues in version 1.0.7.
